{{- if .Values.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
metadata:
  name: {{ template "name" . }}
{{- include "labels" . | indent 2 }}
rules:
{{- range .Values.rbac.rules }}

  {{- if and .nonResourceURLs $.Values.rbac.clusterWideAccess }}
  - nonResourceURLs: ["{{ join "\", \"" .nonResourceURLs }}"]
  {{- else }}
  - apiGroups: ["{{ join "\", \"" (default "*" .apiGroups) }}"]
    resources: ["{{ join "\", \"" (default "*" .resources) }}"]
    verbs: ["{{ join "\", \"" (default "*" .verbs) }}"]
  {{- end }}

{{- end }}
{{- end }}
